export default{
	state:{
		list:[
			{
				checked:false,
				id:1,
				name:"11打客服的和非恶搞认为微软业务打客服的和非恶搞认为微软业务",
				color:"颜色：返回对方的过分的",
				imgUrl:"../../static/img/Children2.jpg",
				pprice:"27",
				num:1
			},
			{
				checked:false,
				id:2,
				name:"22的和非恶搞认为微软业务打客服的和非恶搞认为微软业务",
				color:"颜色：返回对方的过分的",
				imgUrl:"../../static/img/Children2.jpg",
				pprice:"27",
				num:1
			},
		]
	}
}